import type { Metadata } from 'next';
import { Calistoga, Inter } from 'next/font/google';
import './globals.css';
import { twMerge } from 'tailwind-merge';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });
const calistoga = Calistoga({
	weight: ['400'],
	subsets: ['latin'],
	variable: '--font-serif',
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={twMerge(
					inter.variable,
					calistoga.variable,
					'font-sans text-[#F8F8F2] bg-black/95 antialiased'
				)}
			>
				{children}
			</body>
		</html>
	);
}
